### ISSUE TITLE
Help wanted with DynamoDbItemEncryptorException: Configuration mismatch partition or sort key does not exist in item.

### ISSUE THREAD

**Issue by motica1** [aws/aws-database-encryption-sdk-dynamodb-java#393]
Hi,
I am observing an error `software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.model.DynamoDbItemEncryptorException: Configuration mismatch partition or sort key does not exist in item.`  during reading from a global secondary index. The `query` operation returns successfully, but during reading the returned response the above mentioned error occurs. 

Here is everything that i verified:
- Table config includes `plaintextOverride(PlaintextOverride.FORBID_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ)`
- Table description looks accurate 
```
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "pk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "sk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "gsi1_sk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "gsi2_sk",
                "AttributeType": "S"
            }
        ],
        "TableName": "pii-details",
        "KeySchema": [
            {
                "AttributeName": "pk",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "sk",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2023-09-07T14:48:44.776000-04:00",
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": "1969-12-31T19:00:00-05:00",
            "LastDecreaseDateTime": "1969-12-31T19:00:00-05:00",
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 0,
            "WriteCapacityUnits": 0
        },
        "TableSizeBytes": 4524,
        "ItemCount": 4,
        "TableArn": "arn:aws:dynamodb:us-west-2:000000000000:table/pii-details",
        "TableId": "958b7ee0-df96-419d-a378-83fc8e70fca1",
        "BillingModeSummary": {
            "BillingMode": "PAY_PER_REQUEST",
            "LastUpdateToPayPerRequestDateTime": "2023-09-07T14:48:44.776000-04:00"
        },
        "GlobalSecondaryIndexes": [
            {
                "IndexName": "gsi1",
                "KeySchema": [
                    {
                        "AttributeName": "pk",
                        "KeyType": "HASH"
                    },
                    {
                        "AttributeName": "gsi1_sk",
                        "KeyType": "RANGE"
                    }
                ],
                "Projection": {
                    "ProjectionType": "INCLUDE",
                    "NonKeyAttributes": [
                        "identityId",
                        "createdAt",
                        "nickName"
                    ]
                },
                "IndexStatus": "ACTIVE",
                "ProvisionedThroughput": {
                    "ReadCapacityUnits": 0,
                    "WriteCapacityUnits": 0
                },
                "IndexSizeBytes": 4524,
                "ItemCount": 4,
                "IndexArn": "arn:aws:dynamodb:ddblocal:000000000000:table/pii-details/index/gsi1"
            },
            {
                "IndexName": "gsi2",
                "KeySchema": [
                    {
                        "AttributeName": "pk",
                        "KeyType": "HASH"
                    },
                    {
                        "AttributeName": "gsi2_sk",
                        "KeyType": "RANGE"
                    }
                ],
                "Projection": {
                    "ProjectionType": "INCLUDE",
                    "NonKeyAttributes": [
                        "identityId",
                        "createdAt",
                        "nickName"
                    ]
                },
                "IndexStatus": "ACTIVE",
                "ProvisionedThroughput": {
                    "ReadCapacityUnits": 0,
                    "WriteCapacityUnits": 0
                },
                "IndexSizeBytes": 4524,
                "ItemCount": 4,
                "IndexArn": "arn:aws:dynamodb:ddblocal:000000000000:table/pii-details/index/gsi2"
            }
        ],
        "Replicas": []
    }
}
```
- Items are correctly populated in the index, snippet below
```
"Items": [
        {
            "sk": {
                "S": "LATEST#1ff1b931-4a24-46ec-97ec-5ccd54f8ef2a"
            },
            "createdAt": {
                "S": "2023-09-07T18:51:13.634084084Z"
            },
            "pk": {
                "S": "<tenantId>"
            },
            "gsi1_sk": {
                "S": "LATEST#BENEFICIARY"
            },
            "identityId": {
                "S": "1ff1b931-4a24-46ec-97ec-5ccd54f8ef2a"
            },
            "nickName": {
                "S": "nickName"
            }
        },
```
- Using `2.20.86` version of AWS SDK (more context https://github.com/aws/aws-sdk-java-v2/issues/3923#issuecomment-1597924182)
- All the setters for the attributes are public
- Also read [this class](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/81cd84afa06959a133be4e33ab21996361ac0bf3/DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy) where the error is thrown, but i am not sure what is the correct approach here. 

Can you help me with some direction? Also it would be worth adding some examples for `Query` and `Scan` operations for this new encryption client. TIA :)

**Comment by lucasmcdonald3** [comment]
Hi @motica1,

This error would occur when an attribute configured as your partition key or sort key in your `DynamoDbTableEncryptionConfig` object is not present in the item returned by the query.
Could you provide the code you use to create your `DynamoDbTableEncryptionConfig` object? An example is [here](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/BasicPutGetExample.java#L92-L95).
These should be set to the partition key and sort key for the table, not for the GSI.

With respect to Query and Scan examples:
Queries and scans with the AWS SDK for Java using the Database Encryption SDK for DynamoDB are performed the same way as you would without the DB-ESDK.
For examples using these actions, see [this link](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java_dynamodb_code_examples.html).
Our examples primarily focus on how to configure the DB-ESDK in your code to work with the AWS SDK for Java's DynamoDB clients.
We do not explicitly maintain examples demonstrating Queries and Scans because, once you configure your DynamoDB client to use the DB-ESDK, you can perform these actions in the same way as described in AWS SDK for Java documentation.

That said: we have a handful of examples where we create `QueryRequest`s and use those to query our table.
We create these in the same way as the [examples](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java_dynamodb_code_examples.html) for the AWS SDK for Java.
These queries exist in the context of examples for our searchable encryption feature since this feature slightly modifies Query behavior.
You can reference the construction and usage of these queries for your own implementation without setting up searchable encryption.
See [here](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BasicSearchableEncryptionExample.java#L312-L343) for a basic example, or [here](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption) for a directory with more of these examples.

You are correct that we do not have examples demonstrating `Scan` operations.
You can reference the AWS SDK for Java's [examples](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java_dynamodb_code_examples.html) demonstrating Scan operations.

Please provide us with your `DynamoDbTableEncryptionConfig` config and let us know if we can help further.

Best,
Lucas

**Comment by motica1** [comment]
Thank you so much @lucasmcdonald3 for your detailed response. I understand that the config should define partition key and sort key accurately and this is where i think there might be an issue. 

- I am using `DynamoDbEnhancedTableEncryptionConfig` , referencing [the EnhancedPutGetExample](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/EnhancedPutGetExample.java). This is how i define my encryption config and it doesn't have an option to define partition and sort key explicitly in the config.

```
final Map<String, DynamoDbEnhancedTableEncryptionConfig> tableConfigs = new HashMap<>();
tableConfigs.put(
        DDB_TABLE_NAME,
        DynamoDbEnhancedTableEncryptionConfig.builder()
            .logicalTableName(DDB_TABLE_NAME)
            .keyring(kmsKeyRing)
            .allowedUnsignedAttributePrefix(UNSIGN_ATTR_PREFIX)
            .schemaOnEncrypt(TableSchema.fromBean(DetailsDynamoDbBean.class))
            .build());
```
- My schema is such that I share partition key from the base table with GSIs. So essentially i always use the same partition key, with different sort keys (as you would have probably seen from my describeTable output above). My hunch is that my `DynamoDbBean` class is either missing something or i can't use `@DynamoDbPartitionKey` and `@DynamoDbSecondaryPartitionKey(indexNames = {"gsi1", "gsi2"})` on the same attribute. Here is how i define my schema. 

```
@DynamoDbBean
@Data
public class DetailsDynamoDbBean {

  private String pk; // tenantId
  private String sk; // version#identityId
  private String gsi1_sk; // version#identityType
  private String gsi2_sk; // version#nickName
  private String identityId;
  private String createdAt;
  private String nickName;

  @DynamoDbPartitionKey
  @DynamoDbAttribute(value = "pk")
  @DynamoDbSecondaryPartitionKey(indexNames = {"gsi1", "gsi2"})
  public String getPk() {
    return pk;
  }

  @DynamoDbSortKey
  @DynamoDbAttribute(value = "sk")
  public String getSk() {
    return sk;
  }

  @DynamoDbAttribute(value = "gsi1_sk")
  @DynamoDbSecondarySortKey(indexNames = {"gsi1"})
  @DynamoDbEncryptionSignOnly
  public String getGsi1_sk() {
    return gsi1_sk;
  }

  @DynamoDbAttribute(value = "gsi2_sk")
  @DynamoDbSecondarySortKey(indexNames = {"gsi2"})
  @DynamoDbEncryptionSignOnly
  public String getGsi2_sk() {
    return gsi2_sk;
  }

  @DynamoDbAttribute(value = "identityId")
  @DynamoDbEncryptionSignOnly
  public String getIdentityId() {
    return identityId;
  }

  @DynamoDbAttribute(value = "createdAt")
  @DynamoDbEncryptionSignOnly
  public String getCreatedAt() {
    return createdAt;
  }

  @DynamoDbAttribute(value = "nickName")
  @DynamoDbEncryptionSignOnly
  public String getNickName() {
    return nickName;
  }

 
  public void setPk(String pk) {
    this.pk = pk;
  }

  public void setSk(String sk) {
    this.sk = sk;
  }

  public void setGsi1_sk(String gsi1_sk) {
    this.gsi1_sk = gsi1_sk;
  }

  public void setGsi2_sk(String gsi2_sk) {
    this.gsi2_sk = gsi2_sk;
  }

  public void setIdentityId(String identityId) {
    this.identityId = identityId;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public void setNickName(String nickName) {
    this.nickName = nickName;
  }
}
```

**Comment by lucasmcdonald3** [comment]
Hi @motica1,

Thank you for the information!

We released a new version of this library (3.1.0) today that improves error messaging in this situation.
This should help us debug your issue.
Could you update to the latest version (3.1.0) and let us know what error message you see?

Thank you,
Lucas

**Comment by motica1** [comment]
Thank you for the details error handling, i see more descriptive error now. 
`DynamoDbItemEncryptorException: On Decrypt : Partition key 'pk' does not exist in item. Sort key 'sk' does not exist in item. Item contains these attributes : createdAt identityId nickName.`

**Comment by motica1** [comment]
I think i have to include the partition key and sort key in my `attributesToProject`. Let me try that out.

**Comment by motica1** [comment]
well, now i am seeing this error `DynamoDbItemEncryptorException: Encrypted item missing expected header and footer attributes`.  It wasn't there when i ran the test yesterday.
